[versions]
junit = "5.8.2"

[plugins]
dependencyAnalysis = { id = "com.cthing.dependency-analysis", version = "0.1.0-+" }
javaProject = { id = "com.cthing.java-project", version = "0.1.0-+" }
projectSite = { id = "com.cthing.project-site", version = "0.1.0-+" }
yalocc = { id = "com.cthing.yalocc", version = "0.1.0-+" }

[libraries]
assertJ = "org.assertj:assertj-core:3.22.0"
jasypt = "org.jasypt:jasypt:1.9.3"
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
